# Site settings
title: Alex Dautel
email: dautel@hey.com
# url: https://example.github.io
description: "Trail runner"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Alex Dautel

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/howtodowtle
  - title: twitter
    url: https://www.twitter.com/howtodowtle

# Build settings
markdown: kramdown
permalink: pretty
